[package]
<<<<<<< HEAD
name = "rust"
=======
name = "kyopro-rust"
>>>>>>> add prime.rs and template.rs
version = "0.1.0"
authors = ["earlgray283 <earlgray283@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
=======
num = "0.2.1"
permutohedron = "0.2.4"
>>>>>>> add prime.rs and template.rs
